project:
  type: book
  output-dir: _site

execute:
  echo: false

book:
  title: "Shadowdark Clone"
  author: "Ryan Hartman"
  date: "2025-12-17"
  reader-mode: true
  chapters:
    - index.qmd
    - part: Introduction
      chapters:
        - introduction/theBasics.qmd
    - part: Characters
      chapters:
        - characters/index.qmd
    - part: Magic
      chapters:
        - magic/index.qmd
    - part: Gameplay
      chapters:
        - gameplay/index.qmd
    - part: Game Master
      chapters:
        - gm/index.qmd
    - part: Random Encounter Table
      chapters:
        - encounters/index.qmd
    - part: Monsters
      chapters:
        - monsters/index.qmd
    - part: Treasure
      chapters:
        - treasure/index.qmd

format:
  html:
    theme:
      light: cosmo
      dark: solar
    number-depth: 0
    toc-depth: 4
    css: [custom.css, styles.css]
    header-includes: |
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Caudex">
    mainfont: "Caudex"
    include-after-body: toggle-images.html

  pdf:
    template: "custom.tex"
    documentclass: report
    number-depth: 0
    toc: true
    toc-depth: 2
    include-in-header: preamble.tex
    mainfont: "Caudex"
